"""Add return_date to BorrowedBook

Revision ID: 32cd2d89d01c
Revises: 28591e544f21
Create Date: 2025-04-05 23:31:43.944120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cd2d89d01c'
down_revision = '28591e544f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
